# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginReg', '0002_auto_20170131_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=45)),
                ('plan', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traveler', models.ManyToManyField(related_name='trip', to='loginReg.User')),
            ],
        ),
    ]
